-- create
CREATE TABLE EMPLOYEE (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
age TEXT NOT NULL,
address TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Xasan', '18', 'Tashkent');
INSERT INTO EMPLOYEE VALUES (0002, 'Timur', '22', 'Fergana');
INSERT INTO EMPLOYEE VALUES (0003, 'Abudincher', '35', 'Samarqand');
INSERT INTO EMPLOYEE VALUES (0004, 'Otabek', '18', 'Termiz');
INSERT INTO EMPLOYEE VALUES (0005, 'Nodir', '36', 'Xorazm');